Add docs for installing nginx-agent from repository
nginx/agent pull request #309
Opened 2023-05-08 15:33 UTC by Dean-Coakley

### Proposed changes

* Add install instructions for installing from NGINX OSS repository
* Add install instructions for installing from NGINX Plus repository
* Fix typos
* Move logs and systemd info from install doc to getting-started doc
* Add upgrade doc

### Checklist

Before creating a PR, run through this checklist and mark each as complete.

- [x] I have read the [`CONTRIBUTING`](https://github.com/nginx/agent/blob/main/docs/CONTRIBUTING.md) document
- [x] I have run ```make install-tools``` and have attached any dependency changes to this pull request
- [x] If applicable, I have added tests that prove my fix is effective or that my feature works
- [x] If applicable, I have checked that any relevant tests pass after adding my changes
- [x] If applicable, I have updated any relevant documentation ([`README.md`](https://github.com/nginx/agent/blob/main/README.md))
- [x] If applicable, I have tested my cross-platform changes on Ubuntu 22, Redhat 8, SUSE 15 and FreeBSD 13

2023-05-08 15:40 UTC, Jcahilltorre commented on hugo/content/getting-started.md
> +```
```suggestion
```bash
```

2023-05-08 16:04 UTC, Jcahilltorre requested changes
comments + suggestions

2023-05-08 16:04 UTC, Jcahilltorre commented on hugo/content/installation-plus.md
> +First ensure that you are running a supported distribution and architecture: [technical specifications](../technical-specifications/)
```suggestion
First, ensure that you are running a supported distribution and architecture: [technical specifications](../technical-specifications/)
```

2023-05-08 16:04 UTC, Jcahilltorre commented on hugo/content/installation-plus.md
> +  - Next, import an official nginx signing key so `zypper`/`rpm` could verify the packages authenticity. Fetch the key:
```suggestion
  - Next, import an official NGINX signing key so `zypper`/`rpm` can verify the package's authenticity. Fetch the key:
```

2023-05-08 16:04 UTC, Jcahilltorre commented on hugo/content/installation-plus.md
> +  - Next, import an official nginx signing key so apk could verify the packages authenticity. Fetch the key:
```suggestion
  - Next, import an official NGINX signing key so apk can verify the package's authenticity. Fetch the key:
```

2023-05-08 16:04 UTC, Jcahilltorre commented on hugo/content/overview.md
> +docs: "DOCS-1093"
```suggestion
docs: "DOCS-1091"
```

2023-05-08 16:04 UTC, Jcahilltorre commented on hugo/content/technical-specifications.md
> +docs: "DOCS-1094"
```suggestion
docs: "DOCS-1092"
```

2023-05-09 13:11 UTC, craigell commented on hugo/content/installation-oss.md
> +
We should probably include a pre-requisites section that mentions that NGINX OSS is installed and a supported operating system with a link to our supported OS's. Example can be found here https://docs.nginx.com/nginx/admin-guide/installing-nginx/installing-nginx-plus/#prerequisites

2023-05-09 13:15 UTC, craigell commented on hugo/content/installation-oss.md
> +  - Install the prerequisites:
Should include numbered steps to replace of bullet points.

2023-05-09 13:21 UTC, craigell commented on hugo/content/installation-oss.md
> +  - When prompted to accept the GPG key, verify that the fingerprint matches `573B FD6B 3D8F BC64 1079 A6AB ABF5 BD82 7BD9 BF62`, and if so, accept it.
Think we should include a upgrade section for the agent. https://docs.nginx.com/nginx-management-suite/admin-guides/installation/upgrade-guide/#upgrade-nginx-agent

2023-05-10 15:57 UTC, craigell commented on hugo/content/installation-plus.md
> +
Need to add command to this step create repo file in that directory. See step 2 from existing doc https://docs.nginx.com/nginx/admin-guide/installing-nginx/installing-nginx-open-source/#installing-a-prebuilt-rhelcentosoracle-linuxalmalinuxrocky-linux-package-from-the-official-nginx-repository
``` shell
 sudo vi /etc/yum.repos.d/nginx-agent.repo

```

2023-05-17 11:32 UTC, craigell commented on hugo/content/installation-plus.md
Need to add FreeBSD instructions https://docs.nginx.com/nginx/admin-guide/installing-nginx/installing-nginx-plus/#installing-nginx-plus-on-freebsd

2023-05-17 11:34 UTC, craigell commented on hugo/content/installation-oss.md
Need to add FreeBSD instructions

2023-05-18 12:13 UTC, craigell commented on hugo/content/installation-plus.md
> +title: "Install NGINX Agent From NGINX Plus Repository"
Title to change to "Installation from NGINX Plus Repository" to be in line with the OSS title.

2023-05-24 11:42 UTC, Jcahilltorre commented on hugo/content/installation-oss.md
> +- [Installing NGINX Agent on RHEL, CentOS, Rocky Linux, AlmaLinux and Oracle Linux](#installing-nginx-agent-on-rhel-centos-rocky-linux-almalinux-and-oracle-linux)
```suggestion
- [Installing NGINX Agent on RHEL, CentOS, Rocky Linux, AlmaLinux, and Oracle Linux](#installing-nginx-agent-on-rhel-centos-rocky-linux-almalinux-and-oracle-linux)
```

2023-05-24 11:43 UTC, Jcahilltorre commented on hugo/content/installation-oss.md
> +### Installing NGINX Agent on RHEL, CentOS, Rocky Linux, AlmaLinux and Oracle Linux
```suggestion
### Installing NGINX Agent on RHEL, CentOS, Rocky Linux, AlmaLinux, and Oracle Linux
```

2023-05-24 11:43 UTC, Jcahilltorre commented on hugo/content/installation-plus.md
> +- [Installing NGINX Agent on RHEL, CentOS, Rocky Linux, AlmaLinux and Oracle Linux](#installing-nginx-agent-on-rhel-centos-rocky-linux-almalinux-and-oracle-linux)
```suggestion
- [Installing NGINX Agent on RHEL, CentOS, Rocky Linux, AlmaLinux, and Oracle Linux](#installing-nginx-agent-on-rhel-centos-rocky-linux-almalinux-and-oracle-linux)
```

2023-05-24 11:44 UTC, Jcahilltorre commented on hugo/content/installation-plus.md
> +### Installing NGINX Agent on RHEL, CentOS, Rocky Linux, AlmaLinux and Oracle Linux
```suggestion
### Installing NGINX Agent on RHEL, CentOS, Rocky Linux, AlmaLinux, and Oracle Linux
```

2023-05-24 16:27 UTC, craigell approved these changes

2023-05-25 09:02 UTC, merged